<?php

return [
    'flyjinnah_api' => [
        'tax' => 400.00,
    ],
    'tax' => 400.00,
    'tax_code' => 'PKR',
    'contact' => [
        'name' => env('AGENCY_NAME'),
        'phone' => '+92 1234567890',
        'address' => 'Office No. 1113, Plot 111, KS Trade Tower, Shahrah-e-Liaquat, New Chali Road, Karachi, Pakistan',
    ],
    'setting' => [
        'timezone' => env('Asia/Karachi'),
        'admin_email' => 'admin@edestinations.com',
    ],
    'nationalities' => [
        'PK' => ['name' => 'Pakistani', 'code' => '+92'],
        'AF' => ['name' => 'Afghan', 'code' => '+93'],
        'AL' => ['name' => 'Albanian', 'code' => '+355'],
        'DZ' => ['name' => 'Algerian', 'code' => '+213'],
        'US' => ['name' => 'American', 'code' => '+1'],
        'AD' => ['name' => 'Andorran', 'code' => '+376'],
        'AO' => ['name' => 'Angolan', 'code' => '+244'],
        'AG' => ['name' => 'Antiguans', 'code' => '+1-268'],
        'AR' => ['name' => 'Argentinean', 'code' => '+54'],
        'AM' => ['name' => 'Armenian', 'code' => '+374'],
        'AU' => ['name' => 'Australian', 'code' => '+61'],
        'AT' => ['name' => 'Austrian', 'code' => '+43'],
        'AZ' => ['name' => 'Azerbaijani', 'code' => '+994'],
        'BS' => ['name' => 'Bahamian', 'code' => '+1-242'],
        'BH' => ['name' => 'Bahraini', 'code' => '+973'],
        'BD' => ['name' => 'Bangladeshi', 'code' => '+880'],
        'BB' => ['name' => 'Barbadian', 'code' => '+1-246'],
        'BW' => ['name' => 'Batswana', 'code' => '+267'],
        'BY' => ['name' => 'Belarusian', 'code' => '+375'],
        'BE' => ['name' => 'Belgian', 'code' => '+32'],
        'BZ' => ['name' => 'Belizean', 'code' => '+501'],
        'BJ' => ['name' => 'Beninese', 'code' => '+229'],
        'BT' => ['name' => 'Bhutanese', 'code' => '+975'],
        'BO' => ['name' => 'Bolivian', 'code' => '+591'],
        'BA' => ['name' => 'Bosnian', 'code' => '+387'],
        'BR' => ['name' => 'Brazilian', 'code' => '+55'],
        'GB' => ['name' => 'British', 'code' => '+44'],
        'BN' => ['name' => 'Bruneian', 'code' => '+673'],
        'BG' => ['name' => 'Bulgarian', 'code' => '+359'],
        'BF' => ['name' => 'Burkinabe', 'code' => '+226'],
        'MM' => ['name' => 'Burmese', 'code' => '+95'],
        'BI' => ['name' => 'Burundian', 'code' => '+257'],
        'KH' => ['name' => 'Cambodian', 'code' => '+855'],
        'CM' => ['name' => 'Cameroonian', 'code' => '+237'],
        'CA' => ['name' => 'Canadian', 'code' => '+1'],
        'CV' => ['name' => 'Cape Verdean', 'code' => '+238'],
        'CF' => ['name' => 'Central African', 'code' => '+236'],
        'TD' => ['name' => 'Chadian', 'code' => '+235'],
        'CL' => ['name' => 'Chilean', 'code' => '+56'],
        'CN' => ['name' => 'Chinese', 'code' => '+86'],
        'CO' => ['name' => 'Colombian', 'code' => '+57'],
        'KM' => ['name' => 'Comoran', 'code' => '+269'],
        'CG' => ['name' => 'Congolese', 'code' => '+242'],
        'CR' => ['name' => 'Costa Rican', 'code' => '+506'],
        'HR' => ['name' => 'Croatian', 'code' => '+385'],
        'CU' => ['name' => 'Cuban', 'code' => '+53'],
        'CY' => ['name' => 'Cypriot', 'code' => '+357'],
        'CZ' => ['name' => 'Czech', 'code' => '+420'],
        'DK' => ['name' => 'Danish', 'code' => '+45'],
        'DJ' => ['name' => 'Djiboutian', 'code' => '+253'],
        'DO' => ['name' => 'Dominican', 'code' => '+1-809'],
        'NL' => ['name' => 'Dutch', 'code' => '+31'],
        'EC' => ['name' => 'Ecuadorean', 'code' => '+593'],
        'EG' => ['name' => 'Egyptian', 'code' => '+20'],
        'AE' => ['name' => 'Emirati', 'code' => '+971'],
        'ER' => ['name' => 'Eritrean', 'code' => '+291'],
        'EE' => ['name' => 'Estonian', 'code' => '+372'],
        'ET' => ['name' => 'Ethiopian', 'code' => '+251'],
        'FJ' => ['name' => 'Fijian', 'code' => '+679'],
        'FI' => ['name' => 'Finnish', 'code' => '+358'],
        'FR' => ['name' => 'French', 'code' => '+33'],
        'DE' => ['name' => 'German', 'code' => '+49'],
        'GH' => ['name' => 'Ghanaian', 'code' => '+233'],
        'GR' => ['name' => 'Greek', 'code' => '+30'],
        'GT' => ['name' => 'Guatemalan', 'code' => '+502'],
        'HT' => ['name' => 'Haitian', 'code' => '+509'],
        'HN' => ['name' => 'Honduran', 'code' => '+504'],
        'HU' => ['name' => 'Hungarian', 'code' => '+36'],
        'IS' => ['name' => 'Icelander', 'code' => '+354'],
        'IN' => ['name' => 'Indian', 'code' => '+91'],
        'ID' => ['name' => 'Indonesian', 'code' => '+62'],
        'IR' => ['name' => 'Iranian', 'code' => '+98'],
        'IQ' => ['name' => 'Iraqi', 'code' => '+964'],
        'IE' => ['name' => 'Irish', 'code' => '+353'],
        'IL' => ['name' => 'Israeli', 'code' => '+972'],
        'IT' => ['name' => 'Italian', 'code' => '+39'],
        'JM' => ['name' => 'Jamaican', 'code' => '+1-876'],
        'JP' => ['name' => 'Japanese', 'code' => '+81'],
        'JO' => ['name' => 'Jordanian', 'code' => '+962'],
        'KZ' => ['name' => 'Kazakhstani', 'code' => '+7'],
        'KE' => ['name' => 'Kenyan', 'code' => '+254'],
        'KW' => ['name' => 'Kuwaiti', 'code' => '+965'],
        'KG' => ['name' => 'Kyrgyz', 'code' => '+996'],
        'LA' => ['name' => 'Laotian', 'code' => '+856'],
        'LV' => ['name' => 'Latvian', 'code' => '+371'],
        'LB' => ['name' => 'Lebanese', 'code' => '+961'],
        'LR' => ['name' => 'Liberian', 'code' => '+231'],
        'LY' => ['name' => 'Libyan', 'code' => '+218'],
        'LT' => ['name' => 'Lithuanian', 'code' => '+370'],
        'LU' => ['name' => 'Luxembourger', 'code' => '+352'],
        'MY' => ['name' => 'Malaysian', 'code' => '+60'],
        'MV' => ['name' => 'Maldivian', 'code' => '+960'],
        'ML' => ['name' => 'Malian', 'code' => '+223'],
        'MT' => ['name' => 'Maltese', 'code' => '+356'],
        'MX' => ['name' => 'Mexican', 'code' => '+52'],
        'MA' => ['name' => 'Moroccan', 'code' => '+212'],
        'NP' => ['name' => 'Nepalese', 'code' => '+977'],
        'NZ' => ['name' => 'New Zealander', 'code' => '+64'],
        'NG' => ['name' => 'Nigerian', 'code' => '+234'],
        'NO' => ['name' => 'Norwegian', 'code' => '+47'],
        'OM' => ['name' => 'Omani', 'code' => '+968'],
        'PH' => ['name' => 'Filipino', 'code' => '+63'],
        'PL' => ['name' => 'Polish', 'code' => '+48'],
        'PT' => ['name' => 'Portuguese', 'code' => '+351'],
        'QA' => ['name' => 'Qatari', 'code' => '+974'],
        'RO' => ['name' => 'Romanian', 'code' => '+40'],
        'RU' => ['name' => 'Russian', 'code' => '+7'],
        'RW' => ['name' => 'Rwandan', 'code' => '+250'],
        'SM' => ['name' => 'Sammarinese', 'code' => '+378'],
        'ST' => ['name' => 'Sao Tomean', 'code' => '+239'],
        'SA' => ['name' => 'Saudi', 'code' => '+966'],
        'SN' => ['name' => 'Senegalese', 'code' => '+221'],
        'RS' => ['name' => 'Serbian', 'code' => '+381'],
        'SC' => ['name' => 'Seychellois', 'code' => '+248'],
        'SL' => ['name' => 'Sierra Leonean', 'code' => '+232'],
        'SG' => ['name' => 'Singaporean', 'code' => '+65'],
        'SK' => ['name' => 'Slovak', 'code' => '+421'],
        'SI' => ['name' => 'Slovenian', 'code' => '+386'],
        'SO' => ['name' => 'Somali', 'code' => '+252'],
        'ZA' => ['name' => 'South African', 'code' => '+27'],
        'KR' => ['name' => 'South Korean', 'code' => '+82'],
        'ES' => ['name' => 'Spanish', 'code' => '+34'],
        'LK' => ['name' => 'Sri Lankan', 'code' => '+94'],
        'SD' => ['name' => 'Sudanese', 'code' => '+249'],
        'SR' => ['name' => 'Surinamese', 'code' => '+597'],
        'SE' => ['name' => 'Swedish', 'code' => '+46'],
        'CH' => ['name' => 'Swiss', 'code' => '+41'],
        'SY' => ['name' => 'Syrian', 'code' => '+963'],
        'TW' => ['name' => 'Taiwanese', 'code' => '+886'],
        'TJ' => ['name' => 'Tajikistani', 'code' => '+992'],
        'TZ' => ['name' => 'Tanzanian', 'code' => '+255'],
        'TH' => ['name' => 'Thai', 'code' => '+66'],
        'TL' => ['name' => 'Timorese', 'code' => '+670'],
        'TG' => ['name' => 'Togolese', 'code' => '+228'],
        'TT' => ['name' => 'Trinidadian', 'code' => '+1-868'],
        'TN' => ['name' => 'Tunisian', 'code' => '+216'],
        'TR' => ['name' => 'Turkish', 'code' => '+90'],
        'TM' => ['name' => 'Turkmen', 'code' => '+993'],
        'TV' => ['name' => 'Tuvaluan', 'code' => '+688'],
        'UG' => ['name' => 'Ugandan', 'code' => '+256'],
        'UA' => ['name' => 'Ukrainian', 'code' => '+380'],
        'UY' => ['name' => 'Uruguayan', 'code' => '+598'],
        'UZ' => ['name' => 'Uzbekistani', 'code' => '+998'],
        'VU' => ['name' => 'Vanuatuan', 'code' => '+678'],
        'VA' => ['name' => 'Vatican', 'code' => '+379'],
        'VE' => ['name' => 'Venezuelan', 'code' => '+58'],
        'VN' => ['name' => 'Vietnamese', 'code' => '+84'],
        'YE' => ['name' => 'Yemeni', 'code' => '+967'],
        'ZM' => ['name' => 'Zambian', 'code' => '+260'],
        'ZW' => ['name' => 'Zimbabwean', 'code' => '+263']
    ]
];